In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a[0]

1

In [6]:
a[2]

3

In [7]:
a[1]

2

In [8]:
b = [4,5,6]

In [9]:
b_array = np.array(b)

In [10]:
b_array

array([4, 5, 6])

In [11]:
b_array[0]

4

In [12]:
b_array[1]

5

In [13]:
b_array[2]

6

In [14]:
c = (1,2,3,4)

In [15]:
c_array = np.array(c)

In [16]:
type(c_array)

numpy.ndarray

In [17]:
shape(c_array)

NameError: name 'shape' is not defined

In [18]:
c_array.shape()

TypeError: 'tuple' object is not callable

In [19]:
import time

In [20]:
import sys

In [21]:
time_now = time.time()

In [22]:
print(time_now)

1666005839.3740711


In [23]:
time.ctime(time_now)

'Mon Oct 17 16:53:59 2022'

In [24]:
b = range(1000)

In [25]:
b

range(0, 1000)

In [30]:
c = np.array(b)

In [31]:
c

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

to get the size of each integer

In [36]:
print(sys.getsizeof(5))

28


In [37]:
len(b)

1000

In [38]:
print(sys.getsizeof(50))

28


so total size of b array which is formed by using range function of python is?

In [39]:
print(sys.getsizeof(5)*len(b))

28000


Creating the same array using numpy

In [40]:
numpy_array = np.arange(1000)

In [41]:
len(numpy_array)

1000

In [46]:
print(numpy_array.size*numpy_array.itemsize)

8000


In [47]:
print(numpy_array.itemsize)

8


so each item of the numpy array is of size 8 while size of the each list item was 28,

so clearly we can say numpy uses less memory. So there is a significant difference in memory.

2. Let's look at the speed of numpy:

In [51]:
A = np.arange(1000)

In [52]:
B = np.arange(1000)

In [66]:
start_time = time.time()
result1 = A+B                 
end_time = time.time()
print("Execution time is: ", (end_time - start_time)*1000 )

Execution time is:  0.2658367156982422


In [63]:
result1

array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58,   60,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  212,  214,  216,  218,
        220,  222,  224,  226,  228,  230,  232,  234,  236,  238,  240,
        242,  244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
        264,  266,  268,  270,  272,  274,  276,  278,  280,  282,  284,
        286,  288,  290,  292,  294,  296,  298,  3

In [58]:
A1 = range(1000)
B1 = range(1000)

In [64]:
start_time = time.time()
result2 = [(x+y) for x,y in zip(A1,B1)]
end_time = time.time()
print("Execution time is: ", (end_time - start_time)*1000 )

Execution time is:  1.0058879852294922


so we can see execution time of numpy array to do the same stuff is around 25 percent

In [67]:
A

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [68]:
A.size

1000

In [69]:
A.itemsize

8

In [70]:
a = np.array([[1,2], [3,4], [5,6]])

In [71]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
a[0][1]

2

In [73]:
a[2][1]

6

In [74]:
a[2][0]

5

Finding the dimensions of the numpy array

In [75]:
a.ndim

2

In [76]:
a.size

6

In [77]:
a = np.array([[1,2], [3,4], [5,6] , [7,8] ])

In [78]:
a.size

8

In [79]:
a.itemsize

8

In [80]:
a.shape

(4, 2)

In [81]:
a = np.array([[1,2], [3,4], [5,6]])

In [83]:
a.shape

(3, 2)

We can set the data type of the items by using dtype = 

In [84]:
a = np.array([[1,2], [3,4], [5,6]], dtype = np.float64)

In [85]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [86]:
a.itemsize

8

In [91]:
a = np.array([[1,2], [3,4], [5,6]], dtype = np.complex_)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

Creating arrays of zeros and ones, 

Very useful when we are building some neural networks and we need to give some initialisations,

we can use the starting points as zeros or ones as shown:

In [92]:
np.zeros((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [93]:
b = np.ones((4,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
len(b)

4

Size give the total number of elements in the numpy array

In [95]:
b.size

20

In [96]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [97]:
print(np.char.add(["abc","123"],["def", "456"]))

['abcdef' '123456']


In [98]:
print(np.char.multiply("Hello ", 3))

Hello Hello Hello 


In [102]:
print(np.char.center("Hello", 20,fillchar = "-"))

-------Hello--------


Other text based operations uing numpy

In [103]:
print(np.char.capitalize("hello world"))

Hello world


In [104]:
print(np.char.title("hello world"))

Hello World


In [105]:
print(np.char.lower("HELLO world"))

hello world


In [107]:
print(np.char.upper("hello world"))

HELLO WORLD


Splitting by space

In [108]:
print(np.char.split("Python is fun and easy"))

['Python', 'is', 'fun', 'and', 'easy']


Splitting by lines

In [109]:
print(np.char.splitlines("Hello First line \nNext line"))

['Hello First line ', 'Next line']


In [112]:
print(np.char.strip("      Removes leading and trailing spaces    "))

Removes leading and trailing spaces


In [117]:
print(np.char.strip("aaaaaRemoves leading and trailing a'saaaaa",'a'))

Removes leading and trailing a's


In [116]:
print(np.char.join("-","hihihaha"))

h-i-h-i-h-a-h-a


useful when we are processing dates data

In [118]:
print(np.char.join([":","-"],["ymd","dmy"]))

['y:m:d' 'd-m-y']


In [123]:
print(np.char.replace("He is a good dancer", "is" ,"was"))

He was a good dancer


In [124]:
print(np.char.replace("20 04 1995", " ",":"))

20:04:1995


In [125]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
a = ["this" , "is" , "a" , "string" , "array"]

In [128]:
a_numpy_array = np.array(a)

In [129]:
a_numpy_array

array(['this', 'is', 'a', 'string', 'array'], dtype='<U6')

In [130]:
a_numpy_array.ndim

1

In [131]:
a_numpy_array.size

5

In [133]:
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [135]:
np.ones((2,2), dtype = int)

array([[1, 1],
       [1, 1]])